### ISSUE TITLE
Cannot run exe due to missing abseil-cpp symbol

### ISSUE THREAD

**Issue by pachuco** [tareksander/termux-gui-c-bindings#11] opened 2024-01-29 09:59 UTC
```
~/termuxgui $ gcc ./es2gears.c -o gears -lm -lEGL -lGLESv2 -ltermuxgui
~/termuxgui $ ./gears
CANNOT LINK EXECUTABLE "./gears": cannot locate symbol "_ZN4absl12lts_202301255MutexD1Ev" referenced by "/data/data/com.termux/files/usr/lib/libtermuxgui.so"...
~/termuxgui $
```

termux-gui-c is already the newest version (0.1.1).

**Comment by pachuco** [comment] 2024-01-29 14:31
Ah yeah, don't mind folder name, that's just working title for practice projects.

**Comment by tareksander** [comment] 2024-02-11 10:11
I thought I fixed all abseil linking errors, will have to look into it later.

**Comment by pachuco** [comment] 2024-02-11 17:46
dogspeed

**Comment by tareksander** [comment] 2024-02-11 22:27
Can't reproduce the error with a fully updated Termux environment. Have you compiled the C library with CMake or do you use the package?

**Comment by pachuco** [comment] 2024-02-12 12:38
Package.

Termux-app is termux-app_v0.118.0+github-debug_arm64-v8a.apk, version 0.118.0+8e3a898. I think a github action compile.

**Comment by tareksander** [comment] 2024-02-12 13:13
I [created an issue over on termux-packages](https://github.com/termux/termux-packages/issues/19214) for this now,because it seems to work fine when you compile the library on-device with CMake, but is broken in the repo build.

**Comment by tareksander** [comment] 2024-02-12 18:50
Should be fixed once the update hits the package repo and all mirrors.

**Closed as completed by tareksander** 2024-02-12 18:50 UTC
